config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:create, :destroy, :new]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: "static_pages#home"

  match '/help', to: 'static_pages#help'

  match '/about', to: "static_pages#about"

  match 'contact', to: "static_pages#contact"
  

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a(href="http://railstutorial.org/") Rails Tutorial
    by Michael Hartl
  %nav
    %ul
      %li 
        = link_to "About",   about_path
      %li 
        = link_to "Contact", contact_path
      %li 
        %a(href="http://news.railstutorial.org/") News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "sample app", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li
            = link_to "Home",    root_path
          %li
            = link_to "Help",    help_path

          - if signed_in?
            %li
              = link_to "Users", users_path
            %li#fat-menu.dropdown
              %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
                Account
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to "Profile", current_user
                %li
                  = link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method: "delete"
          - else
            %li
              = link_to "Sign in", signin_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?